/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package monprojet;

/**
 *
 * @author Gloire Salva
 */
public class Interfaces2 extends javax.swing.JFrame {

    int heureSyst = 0;
    
    /**
     * Creates new form Interfaces2
     */
    public Interfaces2() {
        initComponents();

                    AlerteHeureSortie alertCyber = new AlerteHeureSortie();
                    AlerteHeureSortie alertBiblio = new AlerteHeureSortie();
                    alertCyber.alerte();
                    alertBiblio.alerteBiblio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AIDE POUR LES INTERFACES DE L'APPLICATION");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 4));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 2));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 102));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 153, 153));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("5)ENREGISTRER UN PAIEMENT\n-------------------------\n\tCe formulaire s'affiche au clic sur le premier bouton \"ENTRER\" du sous formulaire de la gestion des paiements.\nDans la premeière liste déroulante, vous choisirez l'identifiant de l'abonné qui veut effectuer le paiement que vous envisagez enregisitrer et automatiquement, son nom et sa profession apparaitront dans les zones de textes en dessous. Selon sa profession, les montants changeront dans la liste déroulante du montant à payer. Vous n'aurez pas à compléter ni la date de paiement, ni la date d'expiration de l'abonnement pour lequel on effectue le paiement, moins encore le type de l'abonnement. Il suffira juste de choisir le montant, et, grâce aux tarifications enregistrées, le type de l'abonnement se completera automatiquement puis ce dernier va conditionner la date d'expiration. Pour finaliser l'enregistrement, il faudra cliquer sur le bouton \"SAVE\". Vous pourriez modifier un enregistrement en allant dans la barre des menus et cliquer sur Aller à Modifier. Pour modifier une tarification, aller sur le sous-menu de la gestion des paiements puis cliquer sur le bouton ENTRER situé en bas de MODIFICATION DES TARIFS.\n6)ENREGISTRER UNE FREQUENTATION\n-------------------------------\n\tSelon que vous desiriez d'enregistrer une fréquentation du cyber-café ou de la bibliothèque, vous suivrez les mêmes instructions.\nVous n'allez pas compléter la date, celle-ci prenant automatiquement la date de votre système d'exploitation. L'heure d'entrée prend par défaut l'heure de votre système à \n");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 102));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(0, 0, 51));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(0, 153, 153));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("remplies et cliquer sur le bouton \"MODIFIER\".\nRemarques:\n-Pour modifier une fréquentation, vous serez obligés de choisir une date.\n-Pour modifier les données d'un utilisateur, vous serez tenus de compléter correctement son ancien mot de passe, puis compléter le nouveau mot de passe et le confirmer.\n-Veiller à chaque fois choisir une photo pour toutes les interfaces qui vous présentent un lieu d'insertion de la photo.-\n\n   ==========================================\n    LE CONTROLE DES DUREES DES FREQUENTATIONS\n   ==========================================\nUne alerte automatique vous affichera un message reprenant l'identifiant et les noms de l'abonné qui a déjà écouler ses heures. Le message sera accompagné d'un son que vous entendrez si vous êtes éloigné de votre poste de travail. \nAu cas où vous n'avez ni écouter le son ni voir le message, sur le sous-menu des fréquentations(Bibliothèque ou cyber) vous pouvez cliquer sur le bouton \"ENTRER\" placé en bas de l'étiquette \"FREQUENTATIONS ECOULEES\", et toutes les fréquentations du jour qui sont déjà écoulées s'afficheront dans un tableau en commençant par celle qui s'est écoulée en dernier; vous verrez l'identifiant de l'abonné et ses noms.\n\n  En cas d'autres difficultés, n'hésitez pas de     nous contacter(Menu Aide > Contactez-nous).\n\t     @Touts droits réservés\n\t\t Gloire Salva M.");
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        jScrollPane3.setBackground(new java.awt.Color(0, 0, 102));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(0, 0, 51));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(0, 153, 153));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("l'ouverture du formulaire, l'heure de sortie prend par défaut deux heures de plus par rapport à l'heure d'entrée mais vous pourriez la modifier.\nVous devriez alors choisir le motif de la fréquentation et l'ordinateur ou le livre utilisé. Choisissez également l'identifiant de l'abonné là où c'est inscrit en face \"Code Abonné\". Ne soyez pas surpris car tous les abonnés pourront ne pas apparaître, seuls dont les durées d'abonnements sont encore en cours de validité figureront dans cette liste pour éviter ainsi des événtuelles fraudes.\nUn message apparaîtra chaque fois qu'il y aura un abonné dont l'heure de sortie a déjà atteint sa fin et vous écouterez un son d'alerte. Le message contiendra son identifiant et ses noms. \n\nLe bouton \"REFRESH CLOCK\" permet d'actauliser les heures d'entrée et de sortie pour adapter. Il vous est conseillé de cliquer sur ce bouton avant de terminer l'enregistrement.\nPour opérer une modification, cfr les autres points.\n\n   ==========================================\n\t LES INTERFACES DES MODIFICATIONS\n   ==========================================\nPour effectuer une modification, il vous suffira, selon le cas (sur abonné, sur fréquentations, sur ordinateurs, sur livres, ...), de choisir l'identifiant ou le code ou le numéro de l'enregistrement sur lequel vous voulez effectuer des modifications. Ensuite veiller à ce que toutes les cases soient \n");
        jTextArea3.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea3);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/first-32.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Interfaces inter = new Interfaces();
        inter.setLocationRelativeTo(null);
        inter.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaces2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaces2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaces2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaces2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaces2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
