/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package monprojet;

/**
 *
 * @author Gloire Salva
 */
public class Interfaces extends javax.swing.JFrame {

    int heureSyst = 0;
    
    /**
     * Creates new form Interfaces
     */
    public Interfaces() {
        initComponents();

                    AlerteHeureSortie alertCyber = new AlerteHeureSortie();
                    AlerteHeureSortie alertBiblio = new AlerteHeureSortie();
                    alertCyber.alerte();
                    alertBiblio.alerteBiblio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AIDE POUR LES INTREFACES DE L'APPLICATION");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 4));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 2));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 102));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 153, 153));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("   =========================================\n\t     Intreface de Login\n   =========================================\n\tA Cette interface, il vous faut au départ de choisir le mode de connexion(Admin, Bibliothécaire ou Gestionnaire du cyber-café). Chacun des modes de connexion vous rédirige sur le menu compatible. Ensuite, il vous faut entrer un USERNAME(Nom d'utilisateur) puis un mot de passe, les deux doivent être corrects et doivent correspondre avec le mode connexion choisi.\nEnfin, vous pouvez maintenat cliquer sur le bouton \"CONNEXION\" pour accéder à l'interface suivante qui vous offrira un espace de travail selon votre mode de connection.\n\n   =========================================         Les menus selon le type de connexion \n   =========================================\na) MENU PRINCIPAL\n-----------------\n\tCette interface s'affichera lorsque vous vous êtes connecté en tant qu'administrateur. Le menu principal vous donnera accès à toutes les fonctionnalités de l'application. Ici vous pour faire les opérations de gestion sur telle ou telle autre secteur, il vous suffira de cliquer sur le bouton \"ENTRER\" situé en dessous du nom du secteur que vous souhaitez exploiter.\nEn bas de l'interface, le bouton \"VISUALISATION ET IMPRESSION\" servira d'ouvrir un menu pour réaliser des impressions des documents. Le bouton \"VERROUILLER\" vous rédirigera sur la page de connexion (Login), tandis que le bouton \"FERMER\" vous servira à fermer le programme.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 102));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(0, 0, 51));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(0, 153, 153));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Le bouton \"CONFIRMER\" vous servira de finaliser l'enregistrement et vous utiliserez le bouton \"CHOISIR UNE IMAGE\" pour choisir une photo. Grâce à la barre des menus et dans le menu Options vous pourriez aller au formulaire de modification des infos sur un abonné.\n2)AJOUTER UN ORDINATEUR\n-----------------------\n\tCe formulaire s'affiche lorsque vous avez cliqué sur le premier bouton \"ENTRER\" du sous-menu de la gestion des ordinateurs. Une fois ouvert, vous devriez compléter toutes les informations pour enregistrer un nouvel abonné dans la BDD. Les autres directives de l'enregistrement des abonnés peuvent s'appliquer ici.\n3)AJOUTER UN LIVRE\n------------------\n\tCe formulaire s'affiche lorsque vous avez cliqué sur le premier bouton \"ENTRER\" du sous-menu de la gestion des livres. Une fois ouvert, vous devriez compléter toutes les informations pour enregistrer un nouveau livre dans la BDD. Il faudra faire attention au numéro d'exemplaire du livre; pour ce faire, il vous suffira de saisir correctement le titre du livre à enregistrer et tous les livres avec le même titre apparaîtront avec leur numéro d'exemplaire et vous pourriez savoir à combien d'exemplaires vous en êtes. A partir de la barre des menus vous pourriez aller au formulaire de modification.\n4)ENREGISTRER UN UTILISATEUR\n----------------------------\nCe formulaire s'affiche lorsque vous avez cliqué sur le premier bouton \"ENTRER\" du sous-menu de la gestion des utilisateurs. Une fois ouvert, vous devriez compléter toutes les informations et veiller à ce que les mots de passe puissent correspondre pour enregistrer un nouvel utilisateur dans la BDD. Les autres directives de l'enregistrement des abonnés peuvent s'appliquer ici.\n\t");
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        jScrollPane3.setBackground(new java.awt.Color(0, 0, 102));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(0, 0, 51));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(0, 153, 153));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("b) MENU POUR GESTIONNAIRE CYBER\n-------------------------------\n\tCette interface s'ouvre lorsque vous vous êtes connecté en tant que gestionnaire du cyber-café. Ici vous ne pourriez gérer que les ordinateurs et les fréquentations du cyber-café\nc) MENU POUR BIBLIOTHECAIRE\n---------------------------\n\tCette interface s'ouvre lorsque vous vous êtes connecté en tant que bibliothécaire. Ici vous ne pourriez gérer que les livres et les fréquentations de la bibliothèque.\n   ==========================================\n\t\tLES SOUS-MENUS\n   ==========================================\n\tLes sous-menus sont des petites interfaces qui s'ouvrent lorsque vous avez cliqué sur un bouton \"ENTRER\". Sur la majorité d'eux vous trouverez deux opérations dont l'enregistrement et la modification.\nSur les sous-menus de fréquentations pour cyber  et pour bibliothèque, il y a une commande qui    vous permettra d'afficher toutes les fréquentations du jour dont les heures de sortie sont déjà écoulées selon que vous êtes dans la gestion des fréquentations cyber ou celles de bibliothèque.\nSur le sous-menu de gestion des paiements, une commande vous permettra de modifier les modalités des tarifications.\n   ==========================================\n    LES INTERFACES D'ENREGISTREMENTS(AJOUTS)\n   ==========================================\n1)ENREGISTRER UN ABONNE\n-----------------------\n\tCe formulaire s'affiche lorsque vous avez cliqué sur le premier bouton \"ENTRER\" du sous-menu de la gestion des abonnés. Une fois ouvert, vous devriez compléter toutes les informations pour enregistrer un nouvel abonné dans la BDD.");
        jTextArea3.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea3);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/last-32.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Interfaces2 inter = new Interfaces2();
        inter.setLocationRelativeTo(null);
        inter.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaces().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
